ConstrutoraViverSA/Controllers/EstoqueController.cs
using AutoMapper;
using ConstrutoraViverSA.Domain;
using ConstrutoraViverSA.Domain.Enums;
using ConstrutoraViverSA.Models;
using ConstrutoraViverSA.Services;
using Microsoft.AspNetCore.Mvc;
using System;

namespace ConstrutoraViverSA.Controllers
{
    public class EstoqueController : Controller
    {
        private readonly EstoqueService _estoqueService;

        public EstoqueController()
        {
            _estoqueService = new EstoqueService();
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult AdicionarMaterial()
        {
            return View();
        }
        public IActionResult EditarMaterial()
        {
            return View();
        }

        public IActionResult RelatorioMaterial()
        {
            var materiais = _estoqueService.BuscarMateriais();

            var relatorio = new RelatorioModel();
            relatorio.Materiais = materiais;

            return View(relatorio);
        }

        public IActionResult CadastrarMaterial(string Nome, string Descricao, int Tipo, double Valor, DateTime DataValidade)
        {
            Material material = new Material(
                Nome,
                Descricao,
                (TipoMaterialEnum)Tipo,
                Valor,
                DataValidade
                );

            _estoqueService.AdicionarMaterial(material);

            return View("SucessoView");
        }

        public IActionResult BuscarMaterial(long BuscaId)
        {
            var consulta = _estoqueService.BuscarMaterialPorId(BuscaId);

            if (consulta == null)
            {
                return View("ErroView");
            }

            MaterialModel materialModel = new MaterialModel(
                consulta.Id,
                consulta.Nome,
                consulta.Descricao,
                (TipoMaterialEnum)consulta.Tipo,
                Convert.ToDouble(consulta.Valor),
                Convert.ToDateTime(consulta.DataValidade)
                );

            return View("EditarMaterial", materialModel);
        }

        public IActionResult AlterarMaterial(long Id, string Nome, string Descricao, int Tipo, double Valor, DateTime DataValidade)
        {
            var consulta = _estoqueService.BuscarMaterialPorId(Id);

            if (consulta == null)
            {
                return View("ErroView");
            }

            Material materialEditado = new Material(
             Nome,
             Descricao,
             (TipoMaterialEnum)Tipo,
             Valor,
             DataValidade
             );

            _estoqueService.AlterarMaterial(Id, materialEditado);

            return View("SucessoView");
        }
        public IActionResult ExcluirMaterial(long IdExcluir)
        {
            var consulta = _estoqueService.BuscarMaterialPorId(IdExcluir);

            if (consulta == null)
            {
                return View("ErroView");
            }

            _estoqueService.ExcluirMaterial(IdExcluir);

            return View("SucessoView");
        }
    }
}

ConstrutoraViverSA/Controllers/FuncionariosController.cs
using ConstrutoraViverSA.Domain;
using ConstrutoraViverSA.Domain.Enums;
using ConstrutoraViverSA.Models;
using ConstrutoraViverSA.Services;
using Microsoft.AspNetCore.Mvc;
using System;

namespace ConstrutoraViverSA.Controllers
{
    public class FuncionariosController : Controller
    {
        private readonly FuncionarioService _funcionarioService;

        public FuncionariosController()
        {
            _funcionarioService = new FuncionarioService();
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult AdicionarFuncionario()
        {
            return View();
        }
        public IActionResult EditarFuncionario()
        {
            return View();
        }

        public IActionResult RelatorioFuncionario()
        {
            var Funcionario = _funcionarioService.BuscarFuncionarios();

            var relatorio = new RelatorioModel();
            relatorio.Funcionarios = Funcionario;

            return View(relatorio);
        }

        public IActionResult CadastrarFuncionario(string nome, DateTime dataNascimento, int genero, string cpf, string numCtps, string endereco, string email, string telefone, int cargo)
        {
            Funcionario funcionario = new Funcionario(
                nome,
                dataNascimento,
                (GeneroEnum)genero,
                cpf,
                numCtps,
                endereco,
                email,
                telefone,
                (CargoEnum)cargo);

            _funcionarioService.AdicionarFuncionario(funcionario);

            return View("SucessoView");
        }

        public IActionResult BuscarFuncionario(long BuscaId)
        {
            var consulta = _funcionarioService.BuscarFuncionarioPorId(BuscaId);

            if (consulta == null)
            {
                return View("ErroView");
            }

            FuncionarioModel funcionarioModel = new FuncionarioModel(
                consulta.Id,
                consulta.Nome,
                Convert.ToDateTime(consulta.DataNascimento),
                (GeneroEnum)consulta.Genero,
                consulta.Cpf,
                consulta.NumCtps,
                consulta.Endereco,
                consulta.Email,
                consulta.Telefone,
                (CargoEnum)consulta.Cargo
                );

            return View("EditarFuncionario", funcionarioModel);
        }

        public IActionResult AlterarFuncionario(long Id, string nome, DateTime dataNascimento, GeneroEnum genero, string cpf, string numCtps, string endereco, string email, string telefone, CargoEnum cargo)
        {
            var consulta = _funcionarioService.BuscarFuncionarioPorId(Id);

            if (consulta == null)
            {
                return View("ErroView");
            }

            Funcionario funcionarioEditado = new Funcionario(
                 nome,
                 dataNascimento,
                 genero,
                 cpf,
                 numCtps,
                 endereco,
                 email,
                 telefone,
                 cargo);

            _funcionarioService.AlterarFuncionario(Id, funcionarioEditado);

            return View("SucessoView");
        }
        public IActionResult ExcluirFuncionario(long IdExcluir)
        {
            var consulta = _funcionarioService.BuscarFuncionarioPorId(IdExcluir);

            if (consulta == null)
            {
                return View("ErroView");
            }
            _funcionarioService.ExcluirFuncionario(IdExcluir);

            return View("SucessoView");
        }
    }
}

ConstrutoraViverSA/Controllers/ObrasController.cs
using ConstrutoraViverSA.Domain;
using ConstrutoraViverSA.Domain.Enums;
using ConstrutoraViverSA.Models;
using ConstrutoraViverSA.Services;
using Microsoft.AspNetCore.Mvc;
using System;

namespace ConstrutoraViverSA.Controllers
{
    public class ObrasController : Controller
    {
        private readonly ObraService _obraService;
        public ObrasController()
        {
            _obraService = new ObraService();
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult AdicionarObra()
        {
            return View();
        }
        public IActionResult EditarObra()
        {
            return View();
        }

        public IActionResult RelatorioObra()
        {
            var Obras = _obraService.BuscarObras();

            var relatorio = new RelatorioModel();
            relatorio.Obras = Obras;

            return View(relatorio);
        }

        public IActionResult CadastrarObra(string nome, string endereco, TipoObraEnum tipoObra, string descricao, double valor, DateTime prazoConclusao)
        {
            Obra obra = new Obra(
                 nome,
                 endereco,
                 tipoObra,
                 descricao,
                 valor,
                 prazoConclusao);

            _obraService.AdicionarObra(obra);

            return View("SucessoView");
        }
        public IActionResult BuscarObra(long BuscaId)
        {
            var consulta = _obraService.BuscarObraPorId(BuscaId);

            if (consulta == null)
            {
                return View("ErroView");
            }

            ObraModel obraModel = new ObraModel(
                consulta.Id,
                consulta.Nome,
                consulta.Endereco,
                (TipoObraEnum)consulta.TipoObra,
                consulta.Descricao,
                Convert.ToDouble(consulta.Valor),
                Convert.ToDateTime(consulta.PrazoConclusao)
                );

            return View("EditarObra", obraModel);
        }
        public IActionResult AlterarObra(long Id, string nome, string endereco, TipoObraEnum tipoObra, string descricao, double valor, DateTime prazoConclusao)
        {
            var consulta = _obraService.BuscarObraPorId(Id);

            if (consulta == null)
            {
                return View("ErroView");
            }

            Obra ObraEditado = new Obra(
                 nome,
                 endereco,
                 tipoObra,
                 descricao,
                 valor,
                 prazoConclusao);

            _obraService.AlterarObra(Id, ObraEditado);

            return View("SucessoView");
        }
        public IActionResult ExcluirObra(long IdExcluir)
        {
            var consulta = _obraService.BuscarObraPorId(IdExcluir);

            if (consulta == null)
            {
                return View("ErroView");
            }

            _obraService.ExcluirObra(IdExcluir);

            return View("SucessoView");
        }

    }
}

ConstrutoraViverSA/Controllers/OrcamentosController.cs
using ConstrutoraViverSA.Domain;
using ConstrutoraViverSA.Domain.Enums;
using ConstrutoraViverSA.Models;
using ConstrutoraViverSA.Services;
using Microsoft.AspNetCore.Mvc;
using System;

namespace ConstrutoraViverSA.Controllers
{
    public class OrcamentosController : Controller
    {
        private readonly OrcamentoService _orcamentoService;
        public OrcamentosController()
        {
            _orcamentoService = new OrcamentoService();
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult AdicionarOrcamento()
        {
            return View();
        }
        public IActionResult EditarOrcamento()
        {
            return View();
        }

        public IActionResult RelatorioOrcamento()
        {
            var orcamentos = _orcamentoService.BuscarOrcamentos();

            var relatorio = new RelatorioModel();
            relatorio.Orcamentos = orcamentos;

            return View(relatorio);
        }

        public IActionResult CadastrarOrcamento(string Descricao, string Endereco, int TipoObra, DateTime DataEmissao, DateTime DataValidade, double Valor)
        {
            Orcamento orcamento = new Orcamento(
                Descricao,
                Endereco,
                (TipoObraEnum)TipoObra,
                Convert.ToDateTime(DataEmissao),
                Convert.ToDateTime(DataValidade),
                Convert.ToDouble(Valor)
             );

            _orcamentoService.AdicionarOrcamento(orcamento);

            return View("SucessoView");
        }

        public IActionResult BuscarOrcamento(long BuscaId)
        {
            var consulta = _orcamentoService.BuscarOrcamentoPorId(BuscaId);

            if (consulta == null)
            {
                return View("ErroView");
            }

            OrcamentoModel OrcamentoModel = new OrcamentoModel(
                consulta.Id,
                consulta.Descricao,
                consulta.Endereco,
                (TipoObraEnum)consulta.TipoObra,
                Convert.ToDateTime(consulta.DataEmissao),
                Convert.ToDateTime(consulta.DataValidade),
                Convert.ToDouble(consulta.Valor)
                );

            return View("EditarOrcamento", OrcamentoModel);
        }

        public IActionResult AlterarOrcamento(long Id, string Descricao, string Endereco, int TipoObra, DateTime DataEmissao, DateTime DataValidade, double Valor)
        {
            var consulta = _orcamentoService.BuscarOrcamentoPorId(Id);

            if (consulta == null)
            {
                return View("ErroView");
            }

            Orcamento OrcamentoEditado = new Orcamento(
                Descricao,
                Endereco,
                (TipoObraEnum)TipoObra,
                Convert.ToDateTime(DataEmissao),
                Convert.ToDateTime(DataValidade),
                Convert.ToDouble(Valor)
             );

            _orcamentoService.AlterarOrcamento(Id, OrcamentoEditado);

            return View("SucessoView");
        }
        public IActionResult ExcluirOrcamento(long IdExcluir)
        {
            var consulta = _orcamentoService.BuscarOrcamentoPorId(IdExcluir);

            if (consulta == null)
            {
                return View("ErroView");
            }

            _orcamentoService.ExcluirOrcamento(IdExcluir);

            return View("SucessoView");
        }
    }
}

ConstrutoraViverSA/Views/Shared/ErroView.cshtml
<div class="text-center">
    <div class="alert alert-danger">
        <div class="card-body">
            <h5 class="card-title">Não foi possível concluir a operação, tente novamente.</h5>
            <a type="button" class="btn btn-outline-danger" asp-area="" asp-controller="Home" asp-action="Index">Voltar</a>
        </div>
    </div>
</div>

ConstrutoraViverSA/Views/Shared/SucessoView.cshtml
<div class="text-center">
    <div class="alert alert-success">
        <div class="card-body">
            <h5 class="card-title">Operação realizada com sucesso.</h5>
            <a type="button" class="btn btn-outline-success" asp-area="" asp-controller="Home" asp-action="Index">Voltar</a>
        </div>
    </div>
</div>

ConstrutoraViverSA/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/img/logopequena.png" alt="logo" style="width: 40px; height: 40px; "/>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Estoque" asp-action="Index">Estoque</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Funcionarios" asp-action="Index">Funcionários</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Obras" asp-action="Index">Obras</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Orcamentos" asp-action="Index">Orçamentos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <div class="text-center">
        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2021 - Construtora Viver SA
            </div>
        </footer>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>